update status when healthchecker fails to start
submariner-io/submariner pull request #1003
Opened 2020-12-04 14:07 UTC by aswinsuryan

Fixes: #969

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2020-12-04 14:19 UTC, tpantelis approved these changes

2020-12-04 14:19 UTC, tpantelis commented on pkg/cableengine/healthchecker/pinger.go
> +			"IP %q due to %v ", p.ip, err)
```suggestion
		p.failureMsg = fmt.Sprintf("Failed to create the pinger for the remote endpoint IP %q: %v ", p.ip, err)
```

2020-12-04 14:19 UTC, tpantelis commented on pkg/cableengine/healthchecker/pinger.go
> +			"IP %q due to %v ", p.ip, err)
```suggestion
		p.failureMsg = "Failed to start the pinger for the remote endpoint IP %q: %v ", p.ip, err)
```

2020-12-04 14:19 UTC, tpantelis requested changes
Didn't mean to approve :)

2020-12-04 19:51 UTC, tpantelis approved these changes

2020-12-07 10:50 UTC, dfarrell07 approved these changes

2020-12-07 17:37 UTC, skitt approved these changes

2020-12-07 19:04 UTC, merged