Limit the number of times a service is requeued
submariner-io/submariner pull request #1042
Opened 2020-12-17 12:26 UTC by sridhargaddam

Currently, Globalnet works only with kubeproxy iptables driver
and re-uses the IPTable Service Chains created by kubeproxy for
supporting Globalnet ingress use-case for Services.
If there is any issue with kubeproxy or if the cluster uses
kubeproxy with IPVS mode, the IPTable Service Chain will not
be created on the Gateway node and Globalnet continues to
requeue the service waiting for the Chain to be created.
In this PR, we requeue max of 20 times before giving up.

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2020-12-17 16:16 UTC, tpantelis requested changes

2020-12-17 16:16 UTC, tpantelis commented on pkg/globalnet/controllers/ipam/constants.go
> +	GLOBALNET_SVC_MAX_REQUEUES = 20
```suggestion
	maxServiceRequeues = 20
```

2020-12-17 16:16 UTC, tpantelis commented on pkg/globalnet/controllers/ipam/ipam.go
> +						klog.V(log.DEBUG).Infof("Service %s requeued max(%q) allowed iterations, ignoring it",
?

```suggestion
						klog.Warningf("Service %s requeued max(%q) allowed iterations, ignoring it",
```

2020-12-18 13:36 UTC, sridhargaddam reviewed
Thanks for review comments @tpantelis

2020-12-18 15:02 UTC, tpantelis approved these changes

2020-12-18 16:18 UTC, skitt approved these changes

2020-12-18 16:39 UTC, merged