Don't try to remove local cable
submariner-io/submariner pull request #1045
Opened 2020-12-18 01:32 UTC by tpantelis

`RemoveCable` should check if the EP is local like `InstallCable` does.

2020-12-18 15:03 UTC, mangelajo commented
Is this related to an issue? shouldn't the cable engine be able to remove an old endpoint on his own cluster?

2020-12-18 15:09 UTC, tpantelis commented
> Is this related to an issue? shouldn't the cable engine be able to remove an old endpoint on his own cluster?

No reported issue just something I noticed when reviewing logs. We don't install cables for the local cluster - it checks for that in `InstallCable` -  so we should do the same in `RemoveCable` rather than calling the driver for an EP connection we know doesn't exist.  This scenario didn't occur prior to the admiral conversion.

2020-12-22 08:20 UTC, dfarrell07 commented on pkg/cableengine/cableengine.go
> +		klog.V(log.DEBUG).Infof("Not removing cable for local cluster")
```suggestion
		klog.V(log.DEBUG).Infof("Cables are not added/removed for local cluster, skipping removal")
```

To incorporate your explanation?

2020-12-23 13:43 UTC, skitt requested changes
See Daniel’s suggestion, I think it will keep the logs’ meaning clearer in several months’ time when we’ve all forgotten this PR...

2021-01-06 15:04 UTC, skitt approved these changes

2021-01-07 14:40 UTC, mangelajo approved these changes

2021-01-07 15:35 UTC, merged