Fix prep_for_subm.sh predefined "admin" context
submariner-io/submariner pull request #1144
Opened 2021-02-15 07:52 UTC by manosnoam

Signed-off-by: Noam Manos <nmanos@redhat.com>

2021-02-16 13:58 UTC, tpantelis approved these changes

2021-02-16 16:12 UTC, dfarrell07 approved these changes

2021-02-17 01:41 UTC, SteveMattar approved these changes

2021-02-17 01:45 UTC, SteveMattar requested changes

2021-02-17 01:45 UTC, SteveMattar commented on tools/openshift/ocp-ipi-aws/prep_for_subm.sh
> + echo "applying $MACHINESET failed, please make sure kubeconfig current context with a privilaged user" >&2
```suggestion
 echo "applying $MACHINESET failed, please make sure kubeconfig current context with a privileged user" >&2 
```

2021-02-17 09:08 UTC, SteveMattar approved these changes

2021-02-21 08:51 UTC, mangelajo approved these changes

2021-02-21 09:36 UTC, merged