Create GlobalnetEgressIP CRD types and associated items
submariner-io/submariner pull request #1158
Opened 2021-02-24 12:35 UTC by sridhargaddam

This PR adds the necessary types and includes the clientsets,
informers and listers using codegenerator.

Fixes issue: https://github.com/submariner-io/submariner/issues/1157
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-02-24 13:35 UTC, tpantelis commented
Why is the new CRD in `v1alpha1` and not `v1`?

2021-02-24 13:43 UTC, sridhargaddam commented
> Why is the new CRD in `v1alpha1` and not `v1`?

This will be the first implementation of the CRD and there is a potential for changes in the future based on the feedback we get from users. So, I wanted to use v1alpha1. Do you see any problem with this @tpantelis ?

2021-02-24 13:49 UTC, tpantelis commented
> > Why is the new CRD in `v1alpha1` and not `v1`?
> 
> This will be the first implementation of the CRD and there is a potential for changes in the future based on the feedback we get from users. So, I wanted to use v1alpha1. Do you see any problem with this @tpantelis ?

It's not a problem - just wondering what the version progression would be. Would GA release graduate to v1?

2021-02-24 15:01 UTC, sridhargaddam commented
> > > Why is the new CRD in `v1alpha1` and not `v1`?
> > 
> > 
> > This will be the first implementation of the CRD and there is a potential for changes in the future based on the feedback we get from users. So, I wanted to use v1alpha1. Do you see any problem with this @tpantelis ?
> 
> It's not a problem - just wondering what the version progression would be. Would GA release graduate to v1 such that we won't have to worry about supporting/migrating v1alpha1?

Thats a good point @tpantelis . I'd like to hear from @mangelajo, @nyechiel @skitt @mkolesnik if we should go with v1 itself or use v1alpha1.

2021-02-25 14:06 UTC, skitt commented
> > > > Why is the new CRD in `v1alpha1` and not `v1`?
> > > 
> > > 
> > > This will be the first implementation of the CRD and there is a potential for changes in the future based on the feedback we get from users. So, I wanted to use v1alpha1. Do you see any problem with this @tpantelis ?
> > 
> > 
> > It's not a problem - just wondering what the version progression would be. Would GA release graduate to v1 such that we won't have to worry about supporting/migrating v1alpha1?
> 
> Thats a good point @tpantelis . I'd like to hear from @mangelajo, @nyechiel @skitt @mkolesnik if we should go with v1 itself or use v1alpha1.

IMO, as long as we’re not reasonably convinced we won’t need to change the CRD, we should start with v1alpha1.

The GA point in general is a good one, we’ll need to address that sooner rather than later (across all CRDs).

2021-03-02 13:50 UTC, skitt commented
> > > > > Why is the new CRD in `v1alpha1` and not `v1`?
> > > > 
> > > > 
> > > > This will be the first implementation of the CRD and there is a potential for changes in the future based on the feedback we get from users. So, I wanted to use v1alpha1. Do you see any problem with this @tpantelis ?
> > > 
> > > 
> > > It's not a problem - just wondering what the version progression would be. Would GA release graduate to v1 such that we won't have to worry about supporting/migrating v1alpha1?
> > 
> > 
> > Thats a good point @tpantelis . I'd like to hear from @mangelajo, @nyechiel @skitt @mkolesnik if we should go with v1 itself or use v1alpha1.
> 
> IMO, as long as we’re not reasonably convinced we won’t need to change the CRD, we should start with v1alpha1.
> 
> The GA point in general is a good one, we’ll need to address that sooner rather than later (across all CRDs).

I’d missed the fact that all the existing Submariner CRDs are already v1; so let’s stick to that now that we’ve set the precedent.

2021-03-02 13:53 UTC, dfarrell07 requested changes

2021-03-02 13:53 UTC, dfarrell07 commented on pkg/apis/submariner.io/v1alpha1/types.go
> +	// deployed to.
```suggestion
	// deployed.
```

2021-03-02 13:53 UTC, dfarrell07 commented on pkg/apis/submariner.io/v1alpha1/types.go
> +	// The number of globalIP's requested. Globalnet Controller will allocate the requested
```suggestion
	// The number of globalIPs requested. Globalnet Controller will allocate the requested
```

2021-03-02 13:53 UTC, dfarrell07 commented on pkg/apis/submariner.io/v1alpha1/types.go
> +	// In case it is set, its intersected with NamespaceSelector, and only Pods that match the
```suggestion
	// In case it is set, it's intersected with NamespaceSelector, and only Pods that match the
```

2021-03-02 13:53 UTC, dfarrell07 commented on pkg/apis/submariner.io/v1alpha1/types.go
> +	// its considered as an error.
```suggestion
	// it's considered as an error.
```

2021-03-02 18:44 UTC, sridhargaddam commented
v1alpha1 modified lot of existing files and it was kind of mess to revert those changes manually.
I pushed the following PR that uses v1 - https://github.com/submariner-io/submariner/pull/1172

Please review the above PR, thanks.

2021-03-02 18:44 UTC, closed without merging