Add GOVERNANCE.md, answer open gov checklist
submariner-io/submariner pull request #1327
Opened 2021-05-12 18:00 UTC by dfarrell07

The CNCF Sandbox onboarding process asks us to verify that we have open
governance, and points us at the opengovernance.dev checklist used here.

Use the seemingly-standard GOVERNANCE.md file to document Submariner's
status regarding this measure of open governance.

Depends on https://github.com/submariner-io/submariner-website/pull/514
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-05-21 11:27 UTC, mangelajo reviewed
Thanks for creating the doc

2021-05-21 11:27 UTC, mangelajo commented on GOVERNANCE.md
> +  * Submariner is a CNCF Sandbox project, so all Submariner domains are owned by CNCF.
We are still waiting for transfer, right?

2021-05-21 11:27 UTC, mangelajo commented on GOVERNANCE.md
> +  * Submariner is a CNCF Sandbox project, so all Submariner trademarks are owned by the CNCF.
Same I guess.

2021-05-21 17:17 UTC, dfarrell07 commented on GOVERNANCE.md
> +    **TODO: Document this elsewhere.**
Proposed this as authoritative docs: https://github.com/submariner-io/submariner-website/pull/518

2021-05-24 15:37 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * By stepping down or majority vote of Project Owners. **TODO: Document this elsewhere.**
Proposed authoritative docs here: https://github.com/submariner-io/submariner-website/pull/520

2021-05-24 15:37 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * The Submariner Contributors. **TODO: Document this elsewhere.**
Proposed authoritative docs here: https://github.com/submariner-io/submariner-website/pull/520

2021-05-24 15:37 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * The Submariner Project Owners enforce the Code of Conduct ([details](https://submariner.io/community/code-of-conduct)).
Made this more explicit here: submariner-io/submariner-website#520

2021-05-25 13:09 UTC, tpantelis approved these changes

2021-05-25 14:35 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * The Submariner Project Owners enforce the [Code of Conduct](https://submariner.io/community/code-of-conduct), per the Submariner.
```suggestion
  * The Submariner Project Owners enforce the [Code of Conduct](https://submariner.io/community/code-of-conduct), per the Submariner
```

Extra period, sorry.

2021-05-25 14:36 UTC, dfarrell07 commented
FYI, you can see the rendered form here: https://github.com/dfarrell07/submariner/blob/add_gov/GOVERNANCE.md

2021-05-25 14:42 UTC, skitt requested changes

2021-05-25 14:42 UTC, skitt commented on GOVERNANCE.md
> +  * In short, by reviewing code and receiving Committer/Owner approval.
```suggestion
  * In short, by reviewing pull requests and receiving Committer/Owner approval.
```

Documentation PRs also count ;-).

2021-05-25 14:42 UTC, skitt commented on GOVERNANCE.md
> +  * Project Owners are responsible deciding how funds are spent, per the Submariner
```suggestion
  * Project Owners are responsible for deciding how funds are spent, per the Submariner
```

2021-05-25 15:32 UTC, nyechiel approved these changes

2021-05-25 15:48 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * All Submariner code is linted to verify the copyright notices specify "Contributors to the Submariner project", per the
Should maybe link to the linting config: https://github.com/submariner-io/submariner/blob/ed473895ece6dc9be6f9d925a3cfbe441513cf17/.licenserc.json#L22

2021-05-25 15:50 UTC, dfarrell07 commented on GOVERNANCE.md
> +  * All Submariner code is linted to verify the copyright notices specify "Contributors to the Submariner project", per the
Done in the latest.

2021-05-25 16:06 UTC, skitt approved these changes

2021-05-25 16:17 UTC, merged