Accept default public IP setting from environment variable
submariner-io/submariner pull request #1389
Opened 2021-06-07 14:58 UTC by mangelajo

Related-Issue: https://github.com/submariner-io/submariner/issues/1071
Related-Issue: https://github.com/submariner-io/submariner-operator/pull/1406

2021-06-07 15:31 UTC, skitt requested changes
I find the commit message rather confusing — no environment variables are involved in the code that’s changed. Perhaps “Apply PublicIP when specified” would reflect the changes more accurately; the commit message body can go into detail about how this all fits in with the operator... (Incidentally, https://github.com/submariner-io/submariner-operator/pull/1406 doesn’t set `PublicIP`, is that normal?)

2021-06-07 18:28 UTC, mangelajo commented
> I find the commit message rather confusing — no environment variables are involved in the code that’s changed. Perhaps “Apply PublicIP when specified” would reflect the changes more accurately; the commit message body can go into detail about how this all fits in with the operator... (Incidentally, [submariner-io/submariner-operator#1406](https://github.com/submariner-io/submariner-operator/pull/1406) doesn’t set `PublicIP`, is that normal?)

The submariner spec is populated from environment variables (I find it rather confusing myself and I have been tempted to kill that module multiple times because of that)

I will clarify the commit message the variable is SUBMARINER_PUBLICIP

2021-06-08 07:18 UTC, mangelajo commented
@skitt I clarified the commit message, and copied over the PR. Thanks for bringing this up

2021-06-08 07:39 UTC, mangelajo commented
@skitt https://github.com/submariner-io/submariner-operator/pull/1406/files#diff-b530e662ae0c3445396f5d6d16f6018b18ddd298a994cd21e4be39d5e71fad3aR208  I suspectI hadn't pushed the update when you reviewed?

2021-06-08 07:49 UTC, skitt commented
> The submariner spec is populated from environment variables (I find it rather confusing myself and I have been tempted to kill that module multiple times because of that)

Ah, yes, thanks to github.com/kelseyhightower/envconfig...

2021-06-08 07:49 UTC, skitt approved these changes

2021-06-08 07:58 UTC, maayanf24 approved these changes

2021-06-08 08:32 UTC, sridhargaddam approved these changes

2021-06-08 08:55 UTC, merged