OVN: Validate CIDRs in network-plugin-syncer
submariner-io/submariner pull request #1432
Opened 2021-06-27 14:03 UTC by sridhargaddam

In a non-Globalnet deployment with OVN CNI, if the remote CIDRs
overlap with the localCluster CIDRs, an appropriate error message
should be logged and we should avoid making changes to the local
cluster nodes.

Fixes Issue: https://github.com/submariner-io/submariner/issues/1399
Signed-Off-by: Sridhar Gaddam sgaddam@redhat.com

2021-06-27 16:48 UTC, sridhargaddam commented
@mangelajo can you please take a close look and let me know if this is good or if it requires any additional changes?

2021-06-28 09:28 UTC, mangelajo requested changes
added a very-nit comment. Thanks for handling this Sridhar.

2021-06-28 09:28 UTC, mangelajo commented on pkg/networkplugin-syncer/main.go
> +	if err := registry.AddHandlers(logger.NewHandler(), ovn.NewSyncHandler(getK8sClient(), env.ClusterCidr, env.ServiceCidr)); err != nil {
super-nit: let's just pass "env" to avoid adding too many variables.

2021-06-28 09:46 UTC, mangelajo approved these changes
I see the backport was merged before this one, we must make the backports depend-on the devel branch PRs.

https://github.com/submariner-io/submariner/commit/a71559c9778c5d4859e7727945eca8702fc3d4e5

Let's keep it as-is so they are identical.

2021-06-28 10:49 UTC, sridhargaddam commented
> I see the backport was merged before this one, we must make the backports depend-on the devel branch PRs.
> 
> [a71559c](https://github.com/submariner-io/submariner/commit/a71559c9778c5d4859e7727945eca8702fc3d4e5)
> 
> Let's keep it as-is so they are identical.

The backport is a fix done in route-agent OVN handler and is not the same PR.

2021-06-28 11:15 UTC, mangelajo commented
> > I see the backport was merged before this one, we must make the backports depend-on the devel branch PRs.
> > [a71559c](https://github.com/submariner-io/submariner/commit/a71559c9778c5d4859e7727945eca8702fc3d4e5)
> > Let's keep it as-is so they are identical.
> 
> The backport is a fix done in route-agent OVN handler and is not the same PR.

ooops ':) Then ok, let's change it into env, or keep it as is, it's actually not a big deal TBH,

2021-06-28 11:39 UTC, sridhargaddam commented
Updated the PR to pass env

2021-06-28 11:48 UTC, aswinsuryan approved these changes

2021-06-28 11:57 UTC, merged

2021-06-28 12:12 UTC, sridhargaddam commented
Backport for this PR - https://github.com/submariner-io/submariner/pull/1436