Datapath support for GlobalEgressIPs
submariner-io/submariner pull request #1444
Opened 2021-06-29 18:14 UTC by sridhargaddam

This PR implements the datapath support for GlobalEgressIPs
at the namespace level as well as for objects with PodSelectors.

Fixes issue: https://github.com/submariner-io/submariner/issues/1164
Fixes issue: https://github.com/submariner-io/submariner/issues/1165
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-06-30 21:18 UTC, tpantelis requested changes

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/egress_pod_watcher.go
> +	if sel, err := metav1.LabelSelectorAsSelector(podSelector); err == nil {
We should report the error.

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/egress_pod_watcher.go
> +func (w *podWatcher) DelPSetEntry(ipAddress string) error {
```suggestion
func (w *podWatcher) deleteIPSetEntry(ipAddress string) error {
```

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/egress_pod_watcher.go
> +	return nil
```suggestion
	return w.ipSetIface.DelEntry(ipAddress, w.ipSetName)
```

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +	c.podWatchers[key].PodSelector = globalEgressIP.Spec.PodSelector
```suggestion
	podWatcher.PodSelector = globalEgressIP.Spec.PodSelector
```

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +	return equality.Semantic.DeepEqual(oldSelector, newSelector)
This function is simply a one-liner and has one call site and can be inlined.

2021-06-30 21:18 UTC, tpantelis commented on pkg/ipset/fake/ipset.go
> +type FakeIPSet struct {
```suggestion
type IPSet struct {
```

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +		}
Can't we call `programGlobalEgressRules` here?

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +			klog.Errorf("Error destroying the ipSet %q for %q: %v", ipSetName, key, err)
This should really be outside the L355 block b/c on retry it won't re-enter here due to the `podWatcher` removed.

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +	}, globalEgressIP.Status.AllocatedIPs...); requeue {
This could be in a function as it's duplicated with L342.

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/global_egressip_controller.go
> +		delete(c.podWatchers, key)
It seems we should stop the `podWatcher` even if `flushRulesAndReleaseIPs` fails above.

2021-06-30 21:18 UTC, tpantelis commented on pkg/globalnet/controllers/types.go
> +	PodSelector *metav1.LabelSelector
```suggestion
	podSelector *metav1.LabelSelector
```

2021-07-01 08:12 UTC, sridhargaddam commented on pkg/globalnet/controllers/global_egressip_controller.go
> +		}
yes, I think we can. Thanks @tpantelis

2021-07-01 09:04 UTC, sridhargaddam reviewed
Thanks for reviewing @tpantelis

2021-07-01 09:04 UTC, sridhargaddam commented on pkg/globalnet/controllers/global_egressip_controller.go
> +			klog.Errorf("Error destroying the ipSet %q for %q: %v", ipSetName, key, err)
Good point @tpantelis

2021-07-01 12:38 UTC, tpantelis approved these changes

2021-07-01 12:41 UTC, vthapar approved these changes

2021-07-01 13:11 UTC, merged