Configure TCPMTU probe instead of iptable rules
submariner-io/submariner pull request #1479
Opened 2021-07-13 14:01 UTC by aswinsuryan

This enables TCP MTU probing by default with a base mss of 1024.

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2021-07-13 14:50 UTC, skitt requested changes
Is this “instead of iptable rules”? I don’t see any removal of `iptables` calls.

2021-07-13 14:50 UTC, skitt commented on pkg/routeagent_driver/mtu/mtuhandler.go
> +}
Can these be shared with `netlink.go`?

2021-07-13 15:12 UTC, skitt commented on pkg/routeagent_driver/mtu/mtuhandler.go
> +}
Or just use `netlink.New().ConfigureTCPMTUProbe(...)`.

2021-07-13 15:40 UTC, aswinsuryan commented on pkg/routeagent_driver/mtu/mtuhandler.go
> +}
@skitt I guess the API is missing in 0.8.0, I am using that for other branches.

2021-07-13 16:02 UTC, aswinsuryan commented on pkg/routeagent_driver/mtu/mtuhandler.go
> +}
I took this  from https://github.com/submariner-io/submariner/tree/devel/pkg/netlink

2021-07-13 16:19 UTC, skitt commented on pkg/routeagent_driver/mtu/mtuhandler.go
> +}
Oops, sorry, I missed that this was for 0.8!

2021-07-13 16:20 UTC, skitt approved these changes

2021-07-14 13:05 UTC, dfarrell07 approved these changes

2021-07-14 13:22 UTC, tpantelis approved these changes

2021-07-14 14:13 UTC, aswinsuryan commented
Need to wait for the decision on https://github.com/submariner-io/submariner/pull/1480, before merge.

2021-07-21 13:27 UTC, aswinsuryan commented
This is PR does not seems to fix the Openshift AWS- OSP MTU issue. Hence closing.

2021-07-21 13:27 UTC, closed without merging