Implement e2e tests for GlobalEgressIP use-cases
submariner-io/submariner pull request #1497
Opened 2021-07-19 16:19 UTC by sridhargaddam

This PR implements e2e tests that validate globalEgressIPs using NamespaceSelectors
and PodSelectors.

Fixes issue: https://github.com/submariner-io/submariner/issues/1167
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-07-19 20:53 UTC, tpantelis requested changes

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/dataplane/tcp_gn_pod_connectivity.go
> +	When("a pod with NamespaceSelector connects via TCP to the globalIP of a remote service", func() {
```suggestion
	When("a pod matching an egress IP namespace selector connects via TCP to the globalIP of a remote service", func() {
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/dataplane/tcp_gn_pod_connectivity.go
> +	When("a pod with PodSelector connects via TCP to the globalIP of a remote service", func() {
```suggestion
	When("a pod matching an egress IP pod selector connects via TCP to the globalIP of a remote service", func() {
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +		PodSelector := &metav1.LabelSelector{MatchLabels: map[string]string{"test-app": "custom"}}
```suggestion
		podSelector := &metav1.LabelSelector{MatchLabels: map[string]string{"test-app": "custom"}}
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +		Expect(err).To(BeNil())
```suggestion
		Expect(err).To(Succeed())
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +		Expect(err).To(BeNil())
```suggestion
		Expect(err).To(Succeed())
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +func getGlobalEgressIPObj(namespace string, selector *metav1.LabelSelector) (*unstructured.Unstructured, error) {
```suggestion
func newGlobalEgressIPObj(namespace string, selector *metav1.LabelSelector) (*unstructured.Unstructured, error) {
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +		connectorPodGlobalIP = framework.AwaitGlobalEgressIPs(p.FromCluster, geipName, listenerPod.Pod.Namespace)
```suggestion
		connectorPodGlobalIP = framework.AwaitGlobalEgressIPs(p.FromCluster, geipObject.GetName(), listenerPod.Pod.Namespace)
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +		connectorPodGlobalIP = framework.AwaitGlobalEgressIPs(p.FromCluster, geipName, listenerPod.Pod.Namespace)
```suggestion
		connectorPodGlobalIP = framework.AwaitGlobalEgressIPs(p.FromCluster, geipObject.GetName(), listenerPod.Pod.Namespace)
```

2021-07-19 20:53 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +	Expect(connectorPodGlobalIP).ToNot(Equal(""))
```suggestion
	Expect(connectorPodGlobalIP).ToNot(BeEmpty())
```

2021-07-20 07:17 UTC, sridhargaddam reviewed
Thanks for the review comments @tpantelis

2021-07-20 08:08 UTC, mangelajo approved these changes

2021-07-20 11:30 UTC, tpantelis approved these changes

2021-07-20 11:31 UTC, merged