Wrap validation error instead of recreating
submariner-io/submariner pull request #1569
Opened 2021-10-15 12:47 UTC by wangchenglong01

## Which problem is this PR solving?
- Wrap validation error instead of recreating

## Short description of the changes
- Wrap validation error instead of recreating

Depends on submariner-io/releases#241

2021-10-15 13:17 UTC, skitt approved these changes

2021-10-15 14:04 UTC, dfarrell07 approved these changes

2021-10-18 16:25 UTC, wangchenglong01 commented
How to fix the failing of E2E?

2021-10-18 17:17 UTC, dfarrell07 commented
> How to fix the failing of E2E?

That vxlan+ovn test isn't marked as required because they are both new features and seem to still need work. Your PR very likely didn't impact that test, cause the failure. So no need to worry about it, we're just giving some time for folks to review. 

Although folks might be thinking about if this should go in now, right at the end of validating 0.11, or wait until after 0.11.  I'll leave that for others. :) /cc @tpantelis @maayanf24

2021-10-20 11:07 UTC, maayanf24 commented
> > How to fix the failing of E2E?
> 
> That vxlan+ovn test isn't marked as required because they are both new features and seem to still need work. Your PR very likely didn't impact that test, cause the failure. So no need to worry about it, we're just giving some time for folks to review.
> 
> Although folks might be thinking about if this should go in now, right at the end of validating 0.11, or wait until after 0.11. I'll leave that for others. :) /cc @tpantelis @maayanf24

Let's wait and merge this after the release of 0.11

2021-10-25 19:35 UTC, tpantelis requested changes

2021-10-25 19:35 UTC, tpantelis commented on pkg/routeagent_driver/cni/cni_iface.go
> +		return errors.Wrapf(err, "DiscoverCNIInterface returned error")
```suggestion
		return errors.Wrap(err, "Discover returned error")
```

2021-11-18 19:41 UTC, tpantelis approved these changes

2021-11-18 20:39 UTC, merged