Support e2e on single node deployments
submariner-io/submariner pull request #1575
Opened 2021-10-25 11:14 UTC by sridhargaddam

Currently, in e2e, we schedule pods sometimes on gateway nodes and sometimes
on non-gateway nodes to cover a wide range of use-cases. However, when the
same tests are executed on a single node deployments it returns an unfriendly
error message which would be hard to understand. This PR modifies the code
to run only the applicable test-scenarios.

Depends on: https://github.com/submariner-io/shipyard/pull/654
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-10-25 11:15 UTC, sridhargaddam commented
Marking this PR as draft as it's not required for 0.11 release

2021-12-12 06:33 UTC, nyechiel commented
@sridhargaddam is still something we still want to merge?

2021-12-12 06:40 UTC, sridhargaddam commented
> @sridhargaddam is still something we still want to merge?

Yes @nyechiel, its ready for review/merge.

CC: @tpantelis @skitt

2021-12-12 12:50 UTC, tpantelis reviewed
The gateway fail-over test requires at least one node - should check and skip that one too?

2021-12-12 13:02 UTC, tpantelis commented on test/e2e/framework/dataplane.go
> +func IsSingleNodeDeployment(sourceNode, destNode framework.NetworkPodScheduling,
The function name is kind of a misnomer - it's really checking if a connectivity test can be run involving a non-gateway node so how about:

```suggestion
func CanExecuteNonGatewayConnectivityTest(sourceNode, destNode framework.NetworkPodScheduling,
```

2021-12-12 13:32 UTC, sridhargaddam commented
> The gateway fail-over test requires at least one node - should check and skip that one too?

Sure, adding the check. Thanks @tpantelis

2021-12-12 14:11 UTC, tpantelis approved these changes

2021-12-13 09:23 UTC, skitt requested changes

2021-12-13 09:23 UTC, skitt commented on test/e2e/framework/dataplane.go
> +func CanExecuteNonGatewayConnectivityTest(sourceNode, destNode framework.NetworkPodScheduling,
I’m somewhat surprised by this — the function name says we’re determining whether we _can_ run a given test, yet when this function returns `true` we _skip_ tests. Should the booleans be reversed?

2021-12-13 10:02 UTC, sridhargaddam commented on test/e2e/framework/dataplane.go
> +func CanExecuteNonGatewayConnectivityTest(sourceNode, destNode framework.NetworkPodScheduling,
Good observation. Originally this API was IsSingleNodeCluster, so the boolean was apt for that. Let me update it. Thanks @skitt

2021-12-13 10:21 UTC, skitt approved these changes

2021-12-13 13:17 UTC, sridhargaddam commented
Unit test failure does not seem to be related to this PR

```
Summarizing 1 Failure:

[Fail] Pinger when the pinger is stopped [It] should no longer update the statistics 
/go/src/github.com/submariner-io/submariner/pkg/cableengine/healthchecker/pinger_test.go:110
```

2021-12-13 13:35 UTC, tpantelis commented
> Unit test failure does not seem to be related to this PR
> 

Right - likely a timing issue with the test.  I'll take a peek at it.l

2021-12-13 13:56 UTC, merged