Add ADOPTERS.md file, add Red Hat
submariner-io/submariner pull request #1616
Opened 2021-12-07 22:18 UTC by dfarrell07

Add an ADOPTERS.md file to track Submariner's adopters.

Add Red Hat as the initial adopter.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-12-07 22:21 UTC, tpantelis approved these changes

2021-12-08 07:51 UTC, nyechiel commented on ADOPTERS.md
> +| Vendor | Red Hat, Inc. | 2019 | [link](https://www.redhat.com) | Building Submariner into multicluster networking solutions. |
@dfarrell07 any reason not to mention ACM or link to the Submariner+ACM docs?

2021-12-08 08:30 UTC, skitt requested changes
Could you include a reference to the (presumably CNCF) requirement behind this, in the commit message at least?

2021-12-09 08:15 UTC, nyechiel approved these changes

2021-12-09 09:15 UTC, skitt approved these changes

2021-12-09 09:16 UTC, merged