Remove broken link in Twitter, Together! README
submariner-io/submariner pull request #1671
Opened 2022-01-19 19:57 UTC by dfarrell07

This link was flagged by periodic automation, and is in fact broken.

Fixes: #1655
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-01-19 20:29 UTC, tpantelis approved these changes

2022-01-20 08:26 UTC, skitt requested changes
How about fixing the link instead? The working link is

    https://github.com/submariner-io/submariner/new/devel/?filename=tweets/%3Cyour-path%3E.tweet

2022-01-23 17:30 UTC, nyechiel approved these changes

2022-01-23 17:45 UTC, tpantelis approved these changes

2022-01-24 13:01 UTC, skitt approved these changes

2022-01-24 13:01 UTC, merged