Remove cni interface annotation as part of uninstall command
submariner-io/submariner pull request #1729
Opened 2022-03-10 15:40 UTC by yboaron

Submariner Route-agent annotates the cni interface IP in node resource.
This PR ensures that the cni interface IP annotation is deleted as
part of Submariner uninstallation.

Fixes: https://github.com/submariner-io/submariner/issues/1728
Signed-off-by: yboaron <yboaron@redhat.com>

2022-03-11 12:43 UTC, skitt requested changes

2022-03-11 12:43 UTC, skitt commented on pkg/routeagent_driver/cni/cni_iface.go
> +			return errors.Wrap(err, "Discover returned error")
I would suggest an error such as "error retrieving the CNI interface for %s: %v", clusterCidr[0], err instead.

2022-03-15 09:09 UTC, skitt approved these changes

2022-03-15 14:05 UTC, tpantelis approved these changes

2022-03-15 14:07 UTC, sridhargaddam approved these changes

2022-03-15 14:26 UTC, merged

2022-07-21 13:17 UTC, sridhargaddam commented
Backported to release-0.12 branch via https://github.com/submariner-io/submariner/pull/1934