remove redundant parentheses
submariner-io/submariner pull request #1767
Opened 2022-04-01 07:59 UTC by jinglina

remove redundant parentheses

2022-04-01 08:04 UTC, skitt approved these changes

2022-04-01 08:47 UTC, jinglina commented
ready-to-test

2022-04-01 12:05 UTC, tpantelis approved these changes

2022-04-01 12:15 UTC, skitt requested changes

2022-04-01 12:15 UTC, skitt commented on pkg/cableengine/healthchecker/statistics.go
> +		s.sqrDiff += uint64((int64(rtt - oldMean)) * int64(rtt - s.mean))
To pass our linting, the spaces around the `-` operators need to be removed; in addition, there’s another set of parentheses which can be removed:

```suggestion
		s.sqrDiff += uint64(int64(rtt-oldMean) * int64(rtt-s.mean))
```

2022-04-02 00:45 UTC, jinglina commented on pkg/cableengine/healthchecker/statistics.go
> +		s.sqrDiff += uint64((int64(rtt - oldMean)) * int64(rtt - s.mean))
Ok, thanks

2022-04-04 16:31 UTC, dfarrell07 commented
Thanks for bringing this to our attention @jinglina! I think @skitt has a more generic fix here: https://github.com/submariner-io/submariner/pull/1770

2022-04-04 16:36 UTC, skitt commented
> Thanks for bringing this to our attention @jinglina! I think @skitt has a more generic fix here: #1770

@jinglina if you would like to fix your PR, I’d be very happy to rebase mine on top of yours, so you get credit. I don’t want to replace your PR with mine!

2022-04-04 16:53 UTC, dfarrell07 commented
That sounds great, +1 to letting the commit history reflect the development history (and giving credit!).

Just need to fix the Go linting here.

2022-04-06 08:01 UTC, jinglina commented
I will abandon this PR here. Your solution is obviously better. Thanks.

2022-04-06 08:01 UTC, closed without merging