Remove globalIP annotation from node as part of uninstall operation
submariner-io/submariner pull request #1783
Opened 2022-04-10 14:27 UTC by sridhargaddam

Fixes: https://github.com/submariner-io/submariner/issues/1780
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2022-04-19 17:56 UTC, tpantelis requested changes

2022-04-19 17:56 UTC, tpantelis commented on pkg/globalnet/controllers/uninstall.go
> +		}
```suggestion
		annotations := node.GetAnnotations()
		if annotations == nil || annotations[constants.SmGlobalIP] == "" {
			return nil
		}
```

2022-04-20 06:31 UTC, sridhargaddam commented
Thanks for reviewing @tpantelis. The PR should be squashed before merging.

2022-04-20 13:36 UTC, tpantelis approved these changes

2022-04-20 13:51 UTC, aswinsuryan approved these changes

2022-04-24 04:46 UTC, merged