Refactor constants used externally
submariner-io/submariner pull request #1859
Opened 2022-06-03 19:57 UTC by tpantelis

- Move `DefaultNATTDiscoveryPort`, `DefaultUDPPort` and `VxLANPort` to _pkg/ports_ module and rename appropriately. The latter avoids consumers pulling in unwanted dependencies due its prior location under _routeagent_driver_.

- Change `DefaultNATTDiscoveryPort` and `DefaultUDPPort` to int  constants so they don't need to be parsed.

- Move the `NetworkPlugin`* constants under _routeagent_driver_ to _pkg/cni_ and rename appropriately.

2022-06-06 14:28 UTC, dfarrell07 approved these changes

2022-06-07 18:40 UTC, sridhargaddam requested changes
Please find some comments.

JFYI, recently i pushed a PR to use some of these constants in subctl code. I'll update my PR once this PR gets merged. 
https://github.com/submariner-io/subctl/pull/82

2022-06-07 18:40 UTC, sridhargaddam commented on pkg/port/ports.go
> +	UDP           = 4500
```suggestion
	ExternalTunnel           = 4500
```

As this constant can be used by external clients, lets use a bit more descriptive name as UDP is a protocol in itself.

2022-06-07 18:40 UTC, sridhargaddam commented on pkg/port/ports.go
> +	VxLAN         = 4800
```suggestion
	IntraClusterVxLAN         = 4800
```

2022-06-08 06:03 UTC, sridhargaddam approved these changes

2022-06-08 08:30 UTC, merged