Initialize libovsdb clients to any DB
submariner-io/submariner pull request #1882
Opened 2022-06-22 14:05 UTC by astoycos

Setup the libovsdb clients with `WithLeaderOnly(false)`
since the submariner clients are not write intensive
and the changes written to a non-leader db should be
mirrored throughout the cluster.

This allows us to not have to track the DB leader in the
cluster saving some overhead.

Fixes #1878

2022-06-22 14:19 UTC, aswinsuryan approved these changes

2022-06-22 14:36 UTC, tpantelis approved these changes

2022-06-22 14:39 UTC, skitt requested changes
Note that links to the CoreOS Slack aren’t accessible to people outside Red Hat, and should therefore be avoided — if it’s important, it’s better to summarize discussions in the commit message (however the added information isn’t significant here).

2022-06-22 14:39 UTC, skitt commented on pkg/networkplugin-syncer/handlers/ovn/connection.go
> +		libovsdbclient.WithLeaderOnly(false),
We might as well delete this since it’s the default setting:

```suggestion
```

2022-06-22 14:41 UTC, astoycos commented
ACK Agreed @skitt Sorry about that :/

2022-06-22 14:43 UTC, astoycos commented on pkg/networkplugin-syncer/handlers/ovn/connection.go
> +		libovsdbclient.WithLeaderOnly(false),
Done

2022-06-22 15:42 UTC, sridhargaddam approved these changes

2022-06-23 07:10 UTC, skitt approved these changes

2022-06-23 07:11 UTC, merged

2022-06-23 07:12 UTC, nyechiel commented
@skitt can you please make sure this is being backported?

2022-06-23 12:14 UTC, nyechiel commented
@aswinsuryan will handle the backport to `release-0.13`. Thanks!