Allow re-running the plugin scripts
submariner-io/submariner pull request #2222
Opened 2022-12-21 09:09 UTC by sridhargaddam

In an existing KIND deployment when certain make commands are re-run, the external-net plugin script is returning error as the required resources already exist. This PR modifies the script to check if the resource already exists and skip that step.

Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2022-12-22 12:43 UTC, skitt approved these changes

2022-12-25 14:41 UTC, mkolesnik requested changes

2022-12-25 14:41 UTC, mkolesnik commented on scripts/e2e/external/utils
> +    container_name=$2
```suggestion
    local container=$1
```

Use `local` for function local variables.
Also no need to pass the network name as it's always the same.

2022-12-25 14:41 UTC, mkolesnik commented on scripts/e2e/external/utils
> +    docker_create_ext_container ${EXTERNAL_APP} ${EXTERNAL_NET}
```suggestion
    docker inspect --type=container "${EXTERNAL_APP}" > /dev/null 2>&1 || \
        docker run --cap-add=NET_ADMIN --name "$EXTERNAL_APP" --network "$EXTERNAL_NET" \
            -d registry.access.redhat.com/ubi7/ubi python -m SimpleHTTPServer 1234
```

Or more simply (if you add `docker_exists`):

```suggestion
    docker_exists container "${EXTERNAL_APP}" || \
        docker run --cap-add=NET_ADMIN --name "$EXTERNAL_APP" --network "$EXTERNAL_NET" \
            -d registry.access.redhat.com/ubi7/ubi python -m SimpleHTTPServer 1234
```

2022-12-25 14:41 UTC, mkolesnik commented on scripts/e2e/external/utils
> +    create_container_network "${EXTERNAL_NET}" ${EXTERNAL_CIDRS}
```suggestion
    docker inspect --type=network "$EXTERNAL_NET" > /dev/null 2>&1 || \
        docker network create --driver=bridge --subnet="$EXTERNAL_CIDRS" "$EXTERNAL_NET"
```

Or more simply (if you add `docker_exists`):

```suggestion
    docker_exists network "$EXTERNAL_NET" || \
        docker network create --driver=bridge --subnet="$EXTERNAL_CIDRS" "$EXTERNAL_NET"
```

2022-12-25 14:41 UTC, mkolesnik commented on scripts/e2e/external/utils
```suggestion

function docker_exists() {
    local type=$1
    local name=$2
    local format=$3
    docker inspect --type="$type" -f "$format" "$name" > /dev/null 2>&1
}
```

Then you can use it everywhere you want to test if something is in docker.
And yes, omitting the 3rd argument works just fine, e.g. `docker_exists network "$EXTERNAL_NET"` works as you expect.

2022-12-25 14:41 UTC, mkolesnik commented on scripts/e2e/external/utils
> +    docker network connect "${network_name}" "${container_name}"
```suggestion
    docker inspect "$container" -f "{{(index .NetworkSettings.Networks \"${EXTERNAL_NET}\").IPAddress}}" >/dev/null 2>&1 || \
        docker network connect "$EXTERNAL_NET" "$container"
```

Or more simply (if you add `docker_exists`):
```suggestion
    docker_exists container "$container" "{{(index .NetworkSettings.Networks \"${EXTERNAL_NET}\").IPAddress}}" || \
        docker network connect "$EXTERNAL_NET" "$container"
```

2022-12-26 06:17 UTC, sridhargaddam commented on scripts/e2e/external/utils
> +    container_name=$2
Thanks for reviewing @mkolesnik

2022-12-26 14:32 UTC, mkolesnik requested changes

2022-12-26 14:32 UTC, mkolesnik commented on scripts/e2e/external/utils
> +
```suggestion
```

These aren't needed anymore :)

2022-12-26 14:41 UTC, sridhargaddam commented on scripts/e2e/external/utils
> +
Oh yeah, missed removing them.

2022-12-28 08:02 UTC, mkolesnik approved these changes

2023-01-02 15:27 UTC, tpantelis approved these changes

2023-01-02 16:41 UTC, merged