Add FIPS status test
submariner-io/submariner pull request #2232
Opened 2023-01-04 17:54 UTC by MaxBab

Add FIPS status test to verify submariner gateway mode. When OCP cluster deployed with FIPS mode [1], submariner gateway should support FIPS mode and run with this mode enabled for libreswan.

Currently, FIPS is not supported on pure k8s.
It is supported on OCP clusters.
[1] - https://docs.openshift.com/container-platform/4.10/installing/installing-fips.html

Depends On https://github.com/submariner-io/shipyard/pull/1096

Signed-off-by: Maxim Babushkin <mbabushk@redhat.com>

2023-01-16 08:59 UTC, skitt requested changes
Now that we’ve switched to Ginkgo v2, we mustn’t use v1.

2023-01-16 08:59 UTC, skitt commented on test/e2e/dataplane/fips_status.go
> +	. "github.com/onsi/ginkgo"
```suggestion
	. "github.com/onsi/ginkgo/v2"
```

2023-01-16 10:05 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +	. "github.com/onsi/ginkgo"
Done

2023-01-16 11:22 UTC, skitt requested changes

2023-01-16 11:22 UTC, skitt commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("The FIPS mode successfully enabled on gateway pod %q", gwPod.Name))
```suggestion
	By(fmt.Sprintf("FIPS mode is correctly enabled on gateway pod %q", gwPod.Name))
```

2023-01-16 11:53 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("The FIPS mode successfully enabled on gateway pod %q", gwPod.Name))
Done

2023-01-16 12:31 UTC, skitt approved these changes

2023-01-16 14:37 UTC, tpantelis requested changes

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +var _ = Describe("[dataplane] FIPS status reporting", func() {
```suggestion
var _ = Describe("[dataplane] FIPS", func() {
```

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +		It("gateway pod should use the fips mode as part of the libreswan", func() {
```suggestion
	When("FIPS mode is enabled for the active gateway node", func() {
		It("should use FIPS mode in the libreswan cable driver", func() {
```

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +		framework.Skipf("No cluster with FIPS configuration found, skipping the test...")
```suggestion
		framework.Skipf("No cluster found with FIPS enabled, skipping the test...")
```

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintln("Sanity check - find a cluster with FIPS enabled"))
We actually expect that FIPS may not be enabled.

```suggestion
	By(fmt.Sprintln("Find a cluster with FIPS enabled"))
```

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("Found enabled FIPS on cluster %q", fipsClusterName))
Let's move these above L49.

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +		framework.Skipf("No cluster with libreswan cable driver found, skipping the test...")
```suggestion
		framework.Skipf(fmt.Sprintf("Cluster %q is not using the libreswan cable driver, skipping the test...", fipsClusterName))
```

2023-01-16 14:37 UTC, tpantelis commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("FIPS mode is correctly enabled on gateway pod %q", gwPod.Name))
These log messages are outputted by `TestGatewayNodeFIPSMode`.

```suggestion
	f.TestGatewayNodeFIPSMode(fipsCluster, gwPod.Name)
```

2023-01-16 16:09 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +var _ = Describe("[dataplane] FIPS status reporting", func() {
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +		It("gateway pod should use the fips mode as part of the libreswan", func() {
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +		framework.Skipf("No cluster with FIPS configuration found, skipping the test...")
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintln("Sanity check - find a cluster with FIPS enabled"))
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("Found enabled FIPS on cluster %q", fipsClusterName))
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +		framework.Skipf("No cluster with libreswan cable driver found, skipping the test...")
Done

2023-01-16 16:10 UTC, MaxBab commented on test/e2e/dataplane/fips_status.go
> +	By(fmt.Sprintf("FIPS mode is correctly enabled on gateway pod %q", gwPod.Name))
Done

2023-01-16 16:31 UTC, tpantelis approved these changes

2023-01-16 18:59 UTC, merged

2023-01-17 14:40 UTC, dfarrell07 commented
@MaxBab Discussing on the PR scrub, we're a bit on the fence about if this should have a release note, but thinking about users we think they may like to know that they can use this when running in FIPS mode to verify SubM things are actually in FIPS mode. Mind adding a release note?

2023-01-17 15:18 UTC, MaxBab commented
@dfarrell07 

Could you share the details for added the release notes, please?

2023-01-17 15:45 UTC, tpantelis commented
> Could you share the details for added the release notes, please?

After further discussion we decided to [move the FIPS test](https://github.com/submariner-io/submariner/pull/2252) so it's not automatically run by `subctl verify` so no release note needed for this PR.