Dualstack: Ignore IPv6 addresses in mtu_handler
submariner-io/submariner pull request #2294
Opened 2023-02-20 07:16 UTC by sridhargaddam

Partially Fixes: https://github.com/submariner-io/submariner/issues/1739
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-02-20 12:27 UTC, sridhargaddam commented
Sample output of `subctl show all` in a dual-stack k8s cluster:

```
[sgaddam@localhost submariner]$ subctl show all
Cluster "cluster1"
 ✓ Detecting broker(s)
NAMESPACE               NAME                COMPONENTS     GLOBALNET   GLOBALNET CIDR   DEFAULT GLOBALNET SIZE   DEFAULT DOMAINS   
submariner-k8s-broker   submariner-broker   connectivity   no          242.0.0.0/8      65536                                      

 ✓ Showing Connections
GATEWAY           CLUSTER    REMOTE IP    NAT   CABLE DRIVER   SUBNETS                        STATUS      RTT avg.     
cluster2-worker   cluster2   172.21.0.5   no    libreswan      100.67.0.0/16, 10.131.0.0/16   connected   388.079µs    

 ✓ Showing Endpoints
CLUSTER    ENDPOINT IP   PUBLIC IP         CABLE DRIVER   TYPE     
cluster1   172.21.0.4    103.126.231.135   libreswan      local    
cluster2   172.21.0.5    103.126.231.135   libreswan      remote   

 ✓ Showing Gateways
NODE              HA STATUS   SUMMARY                               
cluster1-worker   active      All connections (1) are established   

 ✓ Showing Network details
    Discovered network details via Submariner:
        Network plugin:  kindnet
        Service CIDRs:   [100.66.0.0/16,fd00:1234::/112]
        Cluster CIDRs:   [10.130.0.0/16,fd00:200::/48]

 ✓ Showing versions
COMPONENT               REPOSITORY           VERSION   
submariner-gateway      localhost:5000       local     
submariner-routeagent   localhost:5000       local     
submariner-operator     quay.io/submariner   devel  
```

2023-02-20 12:28 UTC, sridhargaddam commented
All e2e test-cases passed:

```
[SynchronizedAfterSuite] 
github.com/submariner-io/shipyard@v0.15.0-m2/test/e2e/e2e.go:54
[SynchronizedAfterSuite] PASSED [0.000 seconds]
------------------------------

Ran 12 of 44 Specs in 164.556 seconds
SUCCESS! -- 12 Passed | 0 Failed | 0 Pending | 32 Skipped
[sgaddam@localhost submariner]$
```

2023-02-21 12:58 UTC, tpantelis requested changes

2023-02-21 12:58 UTC, tpantelis commented on pkg/cidr/iputil.go
> +func GetIPv4Subnets(cidrList []string) []string {
```suggestion
func ExtractIPv4Subnets(cidrList []string) []string {
```

2023-02-23 18:06 UTC, nyechiel commented
Let's just be clear that this change does not make Submariner support IPv6 based connections or routing, but to leverage and provide IPv4-based connectivity within clusters configured with dual-stack networking.

2023-02-26 09:35 UTC, yboaron commented
Do we plan to add CI gate for dual-stack K8S ?

2023-02-27 06:46 UTC, sridhargaddam commented
> Do we plan to add CI gate for validating IPV4 Submariner on dual-stack K8S ?

Its not on the immediate list of tasks, but we can plan for it as a low/medium priority task.

2023-02-27 08:53 UTC, yboaron commented
> > Do we plan to add CI gate for validating IPV4 Submariner on dual-stack K8S ?
> 
> Its not on the immediate list of tasks, but we can plan for it as a low/medium priority task.


Ack, 
I created https://github.com/submariner-io/submariner/issues/2308

2023-02-27 09:34 UTC, yboaron approved these changes

2023-02-28 17:43 UTC, sridhargaddam commented
@tpantelis can you take a re-look. Updated the PR.

2023-03-01 12:55 UTC, tpantelis approved these changes

2023-03-01 12:55 UTC, merged