Automated backport of #2423: Fix connection issues with RHEL9 GW nodes
submariner-io/submariner pull request #2435
Opened 2023-04-19 07:57 UTC by sridhargaddam

Backport of #2423 on release-0.13.

#2423: Fix connection issues with RHEL9 GW nodes

For details on the backport process, see the [backport requests](https://submariner.io/development/backports/) page.

2023-04-19 12:39 UTC, tpantelis approved these changes

2023-04-19 13:24 UTC, dfarrell07 approved these changes

2023-04-25 05:06 UTC, sridhargaddam commented
@skitt @dfarrell07 e2e is failing for an unrelated error

```
 > [builder 3/3] RUN make -C /go/src/github.com/submariner-io/submariner LOCAL_BUILD=1 bin/linux/amd64/submariner-route-agent:
------
executor failed running [/bin/sh -c make -C ${SOURCE} LOCAL_BUILD=1 bin/${TARGETPLATFORM}/submariner-route-agent]: exit code: 2
make[1]: *** [/opt/shipyard/Makefile.images:24: package/.image.submariner-route-agent] Error 1
make: *** [/opt/shipyard/Makefile.inc:139: e2e] Error 2
[18:12:34.453] [submariner]$ make --debug=b e2e
make: *** [Makefile.dapper:45: e2e] Error 2
Error: Process completed with exit code 2.
```

2023-04-25 07:21 UTC, skitt requested changes

2023-04-25 07:21 UTC, skitt commented on pkg/routeagent_driver/handlers/kubeproxy/vxlan.go
> +			logger.Warningf("Error retrieving reverse path filter for %q: %v", iface, err)
`logger` isn’t defined in 0.13, that’s what’s causing the CI failures.

2023-04-25 08:55 UTC, skitt approved these changes

2023-04-25 09:28 UTC, merged