Automated backport of #2543: Shortening datapath downtime for libreswan cable
submariner-io/submariner pull request #2598
Opened 2023-07-03 13:58 UTC by yboaron

Backport of #2543 on release-0.13.

#2543: Shortening datapath downtime for libreswan cable

For details on the backport process, see the [backport requests](https://submariner.io/development/backports/) page.

2023-07-03 14:14 UTC, dfarrell07 approved these changes

2023-07-04 12:40 UTC, skitt requested changes

2023-07-04 12:40 UTC, skitt commented on pkg/cable/libreswan/libreswan.go
> +			logger.FatalOnError(err, "Error running Pluto")
This isn’t supported on 0.13, you need to use `klog`.

2023-07-05 11:43 UTC, nyechiel approved these changes

2023-07-05 17:10 UTC, sridhargaddam approved these changes

2023-07-10 10:12 UTC, skitt approved these changes

2023-07-10 10:13 UTC, merged