Improve logging in Globalnet controllers
submariner-io/submariner pull request #2739
Opened 2023-10-04 15:01 UTC by sridhargaddam

2023-10-04 17:09 UTC, tpantelis requested changes
In _gateway_monitor.go_, L145 in `handleCreatedOrUpdatedEndpoint`, change:;

`logger.V(log.DEBUG).Infof("In processNextEndpoint, endpoint info: %+v", endpoint)`

to

`logger.V(log.DEBUG).Infof("Gateway monitor informed of create/updated endpoint: %v", endpoint)`

Also similarly,  L231:

`logger.V(log.DEBUG).Infof("Informed of removed endpoint for gateway monitor: %v", endpoint)`

to

`logger.V(log.DEBUG).Infof("Gateway monitor informed of removed endpoint: %v", endpoint)`

2023-10-04 17:09 UTC, tpantelis commented on pkg/globalnet/controllers/base_controllers.go
> +	logger.Infof("Successfully reserved globalIP of %q for %s/%s", reservedIPs, obj.GetNamespace(), obj.GetName())
```suggestion
	logger.Infof("Successfully reserved GlobalIPs %q for %s \"%s/%s\"", reservedIPs, obj.GetKind(), obj.GetNamespace(), obj.GetName())
```

2023-10-04 17:09 UTC, tpantelis commented on pkg/globalnet/controllers/node_controller.go
>  	if node.Name != n.nodeName {
How about:

`logger.Infof("Processing %sd non-gateway node %q - releasing GlobalIP %q", op, node.Name, existingGlobalIP)`

instead of the 2 below.

Also on L189 in `reserveAllocatedIP` below, can you add:

`logger.Infof("Successfully reserved allocated GlobalIP %q for node %q", existingGlobalIP, obj.GetName())
`

2023-10-04 19:50 UTC, tpantelis approved these changes

2023-10-05 07:41 UTC, skitt approved these changes

2023-10-05 09:06 UTC, sridhargaddam commented
@skitt @dfarrell07 the OVN jobs are failing with the following error.

```
/go/pkg/mod/golang.org/x/net@v0.14.0/html/charset/charset.go:20:2: unzip 
/go/pkg/mod/cache/download/golang.org/x/text/@v/v0.12.0.zip: write 
/go/pkg/mod/golang.org/x/text@v0.12.0/unicode/norm/data15.0.0_test.go: no space left on device

FAIL	github.com/submariner-io/submariner/test/e2e [setup failed]
```

2023-10-10 12:29 UTC, merged