Packetfilter: add support for namedset
submariner-io/submariner pull request #2886
Opened 2024-01-25 13:03 UTC by yboaron

Add support for generic namedSet APIs under packetfilter.

2024-01-25 17:52 UTC, tpantelis requested changes

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/packetfilter.go
> +type Named interface {
I think this should be called `NamedSet` as this is what consumers will store and use continuously.  The struct above is referenced once as input so I suggest `SetConfig` or `SetInfo`.

```suggestion
type NamedSet interface {
```

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/packetfilter.go
> +	NewNamed(set *NamedSet) Named
```suggestion
	NewNamedSet(set *NamedSet) Named
```

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/packetfilter.go
> +	DestroySet(set string) error
We really don't need this method. It's used in [one place](https://github.com/submariner-io/submariner/blob/636b457da21542ec3a7632143562c220c57e4f55/pkg/globalnet/controllers/uninstall.go#L106) to destroy all sets with a name prefix but the consumer can create a `NamedSet` and call `Destroy`. But I think a better alternative is to replace `ListSets` with a general `DestroySets` that takes a name filter:

`DestroySets(nameFilter func(string) bool) error`

Ideally `ListSets` would return a `NamedSet` but the ipset lib doesn't have a way to retrieve a set's params after creation so perhaps it's best not to expose just set names.

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/iptables/iptables.go
> +	IPSetIface ipset.Interface
Let's not export this.

```suggestion
	ipSetIface ipset.Interface
```

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/iptables/namedset.go
> +	}, a.IPSetIface)
I think we should move the `Named` implementation in ipset here as we expect consumers to use the API in packetfilter. We could move all the ipset code here as well but I think it makes sense to keep that in its own package as we inherited it from somewhere else.

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +type setInterface interface {
I'm not clear on the purpose of this local interface. This seems to be patterned after `ipset.Interface` but we don't need all these methods.

2024-01-25 17:52 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +	iface setInterface
Just use `PacketFilter` directly.

```suggestion
	pfilter *PacketFilter
```

2024-01-29 13:20 UTC, tpantelis requested changes

2024-01-29 13:20 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +type namedType struct {
Minor thing but more clear.

```suggestion
type namedSet struct {
```

2024-01-29 13:20 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +	return errors.Wrap(n.pfilter.destroySet(n.setInfo.Name), "Destroy failed")
Minor but we should need to wrap here nor in the methods below.

```suggestion
	return n.pfilter.destroySet(n.setInfo.Name)
```

2024-01-29 13:20 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +	return nil
`delete` handles nil

```suggestion
	delete(i.sets, setName)

	return nil
```

2024-01-29 13:20 UTC, tpantelis commented on pkg/packetfilter/fake/namedset.go
> +			}
```suggestion
			delete(i.sets, setName)
```

2024-01-29 13:20 UTC, tpantelis commented on pkg/packetfilter/iptables/namedset.go
> +type namedType struct {
```suggestion
type namedSet struct {
```

2024-01-31 12:37 UTC, tpantelis approved these changes

2024-02-01 14:05 UTC, yboaron commented
cc @sridhargaddam

2024-02-01 16:13 UTC, sridhargaddam commented on pkg/packetfilter/fake/namedset.go
> +type namedType struct {
Its just a minor thing, but just want to check if you wanted to use namedSet here? (as the conversation is marked as resolved).

2024-02-01 16:16 UTC, sridhargaddam commented on pkg/packetfilter/fake/namedset.go
> +		return fmt.Errorf("IP set %q does not exist", nSet.Name)
```suggestion
		return fmt.Errorf("named set %q does not exist", nSet.Name)
```

2024-02-02 07:56 UTC, yboaron commented on pkg/packetfilter/fake/namedset.go
> +type namedType struct {
> Its just a minor thing, but just want to check if you wanted to use namedSet here? (as the conversation is marked as resolved).

Ooops,   missed it. 
thanks

2024-02-02 08:21 UTC, sridhargaddam approved these changes

2024-02-04 08:50 UTC, merged