Add CRDs for Route-Agent Health Checker
submariner-io/submariner pull request #3079
Opened 2024-07-13 01:39 UTC by aswinsuryan

Add a CRD for routeagent status. There will be status  CR per route agent.

2024-07-13 11:10 UTC, tpantelis requested changes

2024-07-13 11:10 UTC, tpantelis commented on pkg/apis/submariner.io/v1/types.go
> +	Spec          EndpointSpec     `json:"endpoint"`
```suggestion
	Spec          EndpointSpec     `json:"spec"`
```

2024-07-16 17:20 UTC, aswinsuryan commented on pkg/apis/submariner.io/v1/types.go
> +	Spec          EndpointSpec     `json:"endpoint"`
Done.

2024-07-16 19:27 UTC, tpantelis approved these changes

2024-07-16 19:28 UTC, tpantelis commented on pkg/apis/submariner.io/v1/types.go
> +
Need RouteAgentList as well.

2024-07-16 20:49 UTC, aswinsuryan commented on pkg/apis/submariner.io/v1/types.go
> +
Done.

2024-07-17 13:31 UTC, vthapar approved these changes

2024-07-17 15:36 UTC, merged