Automated backport of #3121: Add retry mechanism to CNI interface discovery on kube-proxy
submariner-io/submariner pull request #3139
Opened 2024-08-21 09:13 UTC by yboaron

Backport of #3121 on release-0.17.

#3121: Add retry mechanism to CNI interface discovery on kube-proxy

For details on the backport process, see the [backport requests](https://submariner.io/development/backports/) page.

2024-08-21 09:40 UTC, skitt approved these changes

2024-08-21 09:44 UTC, skitt requested changes
This requires the route agent refactor which was done for 0.18.

2024-08-21 11:56 UTC, tpantelis approved these changes

2024-08-21 13:28 UTC, dfarrell07 approved these changes

2024-08-28 07:54 UTC, skitt approved these changes

2024-08-28 07:54 UTC, merged