Merge the package owners, align entries
submariner-io/submariner pull request #810
Opened 2020-09-15 15:12 UTC by skitt

package/* is associated with mkolesnik, /package/* with skitt, this
merges both entries so that shared ownership actually works.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2020-09-15 15:31 UTC, tpantelis approved these changes

2020-09-16 15:23 UTC, dfarrell07 approved these changes

2020-09-16 15:25 UTC, dfarrell07 commented
I think the package owner overlap is no longer there? But the file could still use some alignment help imho.

2020-09-16 15:26 UTC, dfarrell07 requested changes
I think the package owner overlap is no longer there? But the file could still use some alignment help imho.

2020-09-17 07:27 UTC, mangelajo commented
It was handled here: https://github.com/submariner-io/submariner/pull/812/files

2020-09-17 07:27 UTC, closed without merging